---
- hosts: all
  become: true
  remote_user: ubuntu
  become_method: sudo
  vars: 
    ansible_ssh_private_key_file: ~/GreenKeys/dev_jese_chavez_20222012.pem
  tasks:
  
  - name: Copy dockerfiles and other necessary files
    copy:
      src: ./ssm_seguridad-guard-patrol-web-app
      dest: /home/ubuntu

  - name: Docker compose up in dettach mode 
    command: chdir=/home/ubuntu/ssm_seguridad-guard-patrol-web-app/ docker compose up -d
  
  - name: Restart Nginx
    shell: systemctl restart nginx