---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - ./variables.yml
  vars: 
    ansible_ssh_private_key_file: '{{ instance_ssh_key_path }}'
  tasks:

  - name: 'Update and Upgrade apt packages.'
    apt: update_cache=yes upgrade=yes cache_valid_time=3600
    when: apt_packages_names

  - name: 'Add signing keys.'
    apt_key: 
      url: '{{ item }}' 
      state: present
    loop: '{{ apt_signing_keys }}'
    when: apt_signing_keys

  - name: 'Set up apt repositories.'
    apt_repository:
      repo: '{{ item }}'
      state: present
    loop: '{{ apt_repositories }}'
    when: apt_repositories
  
  - name: 'Update and install apt packages.'
    apt:
      update_cache: true
      name: '{{ apt_packages_names }}'
    when: apt_packages_names

  - name: 'Update and install apt packages. (force apt-get)'
    apt:
      update_cache: true
      force_apt_get: true
      name: '{{ forced_apt_get_packages_names }}'
    when: forced_apt_get_packages_names