---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - ./variables.yml
  vars:
    ansible_ssh_private_key_file: '{{ instance_ssh_key_path }}'
  tasks:
  - name: 'Requests domains certificates (nginx plugin)'
    shell: >
      certbot --nginx 
      --agree-tos
      --email '{{ item.value.certbot_email }}'
      -d '{{ item.key }}'
      --non-interactive
    loop: "{{ lookup('ansible.builtin.dict', nginx_domains_config) }}"

  - name: 'Auto renewal certificate timer.'
    systemd: 
      name: certbot.timer
      state: started
      enabled: true

  - name: 'Restarts Nginx after requesting certificates.'
    shell: systemctl restart nginx