---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars: 
    ansible_ssh_private_key_file: ~/GreenKeys/dev_jese_chavez_20222012.pem
  tasks:

  - name: Update and Upgrade
    apt: update_cache=yes upgrade=yes cache_valid_time=3600

  - name: Add nginx_signing.key
    apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

  - name: set up apt repository of nginx (debsrc)
    apt_repository:
      repo: deb-src http://nginx.org/packages/ubuntu/ xenial nginx

  - name: set up apt repository of nginx (deb)
    apt_repository:
      repo: deb http://nginx.org/packages/ubuntu/ xenial nginx

  - name: set up apt repository of certbot 
    apt_repository:
      repo: ppa:certbot/certbot
      state: present

  - name: update and install nginx
    apt:
      update_cache: yes
      name: nginx

  - name: update and install software-properties-common
    apt:
      update_cache: yes 
      name: software-properties-common
  
  - name: update and install certbot
    apt:
      update_cache: yes 
      name: certbot

  - name: update and install python3-certbot-nginx
    apt:
      update_cache: yes 
      name: python3-certbot-nginx