---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - ./variables.yml
  vars: 
    ansible_ssh_private_key_file: '{{ instance_ssh_key_path }}'
  tasks:
  - name: 'Set up nginx directories to allow virtual host definition.'
    block:
    - name: 'Creates nginx sites-available directory'  
      file:
        path: '/etc/nginx/{{ nginx_sites_available_folder_name }}/'
        state: directory
    
    - name: 'Creates nginx sites-enabled directory'
      file:
        path: '/etc/nginx/{{ nginx_sites_enabled_folder_name }}/'
        state: directory

  - name: 'Creates server blocks files at sites-available directory.'
    shell: |
      echo 'server {
          listen {{ item.value.listen_port }};
          server_name {{ item.key }};
          location / {
            proxy_pass {{ item.value.proxy_pass }};
          }
        }' > '/etc/nginx/{{ nginx_sites_available_folder_name }}/{{ item.key }}'
    loop: "{{ lookup('ansible.builtin.dict', nginx_domains_config) }}"
  
  - name: 'Creates symlinks to sites-available directory.'
    file:
      src: '/etc/nginx/{{ nginx_sites_available_folder_name }}/{{ item.key }}'
      dest: '/etc/nginx/{{ nginx_sites_enabled_folder_name }}/{{ item.key }}'
      state: link
    loop: "{{ lookup('ansible.builtin.dict', nginx_domains_config) }}"
  
  - name: 'Enable server blocks routing.'
    block:
    - name: 'Add sites-enabled to nginx.conf file.'
      shell: |
        sed -i '$i'"\ \ \ \ \include /etc/nginx/{{ nginx_sites_enabled_folder_name }}/*;" /etc/nginx/nginx.conf

    - name: 'Restarts Nginx after enabling the corresponding server blocks'
      shell: systemctl restart nginx

  # - name: Request SSL cert and auto-renew with certbot for admin and api services
  #   block:
  #   - name: Request SSL cert and auto-renew with certbot for api service
  #     shell: certbot --nginx --agree-tos --email jeseabraham.chavez@builtbybamboo.com -d dev-api.ssmseguridad.com --non-interactive 
    
  #   - name: Request SSL cert and auto-renew with certbot for admin service
  #     shell: certbot --nginx --agree-tos --email jeseabraham.chavez@builtbybamboo.com -d dev-admin.ssmseguridad.com --non-interactive
  
  # - name: Restarts Nginx after requesting SSL cert and auto-renew
  #   shell: systemctl restart nginx
    
  # - name: Enable and Start certbot timer
  #   systemd:
  #     name: certbot.timer
  #     state: started
  #     enabled: yes