---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars: 
    ansible_ssh_private_key_file: ~/GreenKeys/dev_jese_chavez_20222012.pem
  tasks:
  - name: Set up nginx directories to allow server blocks
    block:
    - name: Creates nginx sites-available directory  
      file:
        path: /etc/nginx/sites-available/
        state: directory
    
    - name: Creates nginx sites-enabled directory  
      file:
        path: /etc/nginx/sites-enabled/
        state: directory

  - name: Copy local server blocks for api and admin services
    block:
      - name: Copy dev-api.ssmseguridad.com server block
        copy:
          src: ./dev-api.ssmseguridad.com
          dest: /etc/nginx/sites-available/dev-api.ssmseguridad.com 

      - name: Copy dev-admin.ssmseguridad.com server block
        copy:
          src: ./dev-admin.ssmseguridad.com
          dest: /etc/nginx/sites-available/dev-admin.ssmseguridad.com 
  
  - name: Activate services server blocks
    block:
    - name: Symlink for dev-api.ssmseguridad.com 
      file:
        src: /etc/nginx/sites-available/dev-api.ssmseguridad.com 
        dest: /etc/nginx/sites-enabled/dev-api.ssmseguridad.com
        state: link

    - name: Symlink for dev-admin.ssmseguridad.com
      file:
        src: /etc/nginx/sites-available/dev-admin.ssmseguridad.com 
        dest: /etc/nginx/sites-enabled/dev-admin.ssmseguridad.com
        state: link


  - name: Enable server blocks routing
    block:
    - name: Replace default nginx.conf for local file
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restarts Nginx after enabling the corresponding server blocks
      shell: systemctl restart nginx

  - name: Request SSL cert and auto-renew with certbot for admin and api services
    block:
    - name: Request SSL cert and auto-renew with certbot for api service
      shell: certbot --nginx --agree-tos --email jeseabraham.chavez@builtbybamboo.com -d dev-api.ssmseguridad.com --non-interactive 
    
    - name: Request SSL cert and auto-renew with certbot for admin service
      shell: certbot --nginx --agree-tos --email jeseabraham.chavez@builtbybamboo.com -d dev-admin.ssmseguridad.com --non-interactive
  
  - name: Restarts Nginx after requesting SSL cert and auto-renew
    shell: systemctl restart nginx
    
  - name: Enable and Start certbot timer
    systemd:
      name: certbot.timer
      state: started
      enabled: yes