---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - ./variables.yml
  vars: 
    ansible_ssh_private_key_file: '{{ instance_ssh_key_path }}'
    local_files_path: '{{ compose_files_paths.local_files_path }}'
    remote_files_path: '{{ compose_files_paths.remote_files_path }}'
  tasks:
  # It should be a set of images located on a container registry.
  - name: 'Copy dockerfiles and other necessary files.'
    copy:
      src: '{{ local_files_path }}'
      dest: '{{ remote_files_path }}'

  - name: 'Creates .env file based on .env.example.'
    command: cp .env.example .env
    args: 
      chdir: "{{ remote_files_path }}/{{ local_files_path | split('/') | last }}"
      
  
  - name: 'Docker compose Up.'
    command: docker compose up --detach
    args: 
      chdir: "{{ remote_files_path }}/{{ local_files_path | split('/') | last }}"